[package]
name = "autophagy-mlir"
version = "0.1.0"
edition = "2021"

[dependencies]
autophagy = { version = "0.1", path = "../autophagy" }
melior = "0.8"
quote = "1.0.28"
syn = "2.0.16"
train-map = "0.1.0"
