name: document
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - run: tools/setup.sh
      - run: cargo doc
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc
      - uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'
