name: lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - run: tools/setup.sh
      - run: cargo clippy -- -D warnings
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt -- --check
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@main
        with:
          files: "**/*.{md,rs,sh,toml}"
  unused_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup install nightly
      - uses: Swatinem/rust-cache@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - run: tools/setup.sh
      - run: |
          rustup run nightly cargo install cargo-udeps
          cargo +nightly udeps
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
